### ISSUE TITLE
Earmarking Modality: digitise and publish

### ISSUE THREAD

**Issue by stevieflow** [codeforIATI/Unofficial-Codelists#129]
I think this codelist is a candidate for digitisation!

I've made a first draft of this: https://docs.google.com/spreadsheets/d/1o1SQDqfFTBgUJO2k83mfFlLtgpwUUkEbc3gjRgIWJSo/edit#gid=0

The description - and possibly remarks - need adding.  The formatting is horrible in the source, so copy and paste is not too hel p fu l !

The source is page 16 of a PDF: https://reliefweb.int/sites/reliefweb.int/files/resources/Grand_Bargain_final_22_May_FINAL-2.pdf

@markbrough @davidmegginson what do you think?

**Comment by davidmegginson** [comment]
It's a good list — I think Helen Campbell put it together through BRC on behalf of CaLP — but I'm not sure how much use it's getting in real life, if any. Is our goal in Code for IATI to follow by making popular codelists more easily available, or to lead by making codelists available in the hope that they become popular? (Sincere question.)

**Comment by markbrough** [comment]
I think this is a very good question @davidmegginson -- I think a bit of both? You are right -- it is not getting much takeup at all in real life. But I still think there could be an argument for digitising and sharing it, even if it is just something that third parties might map to, rather than actually publish in their data?

**Comment by andylolz** [comment]
> I think a bit of both? You are right -- it is not getting much takeup at all in real life.

One handy thing about adding it is: it makes it a bit easier to see takeup, because it will show up in the usage stats on the codeforIATI dashboard (on this page: https://dashboard.codeforiati.org/codelists.html)

It’s already been added as a vocab that can be used in IATI data, so I think it’s probably worth replicating it. I’ve had a go at doing this manually in #141.

[Another generally cool thing is: If there is a digital source for a codelist, we can add an importer to [codeforIATI/codelist-updater](https://github.com/codeforIATI/codelist-updater) and then we get notified by pull requests when the source changes. So the barrier to adding more replicated codelists is hopefully low.]

**Comment by matmaxgeds** [comment]
FYI - I think this may be another source for the same list? https://interagencystandingcommittee.org/system/files/2020-04/Multi-year%20and%20flexible%20funding%20-%20Definitions%20Guidance%20Summary%20-%20Narrative%20Section%20January%202020.pdf - Edit: seems not!
